spring:
  security:
    saml2:
      relyingparty:
        registration:
          auth0:
            assertingparty:
              metadata-uri: https://dev-t5ujmd1ghjgaud8e.eu.auth0.com/samlp/metadata/IDjyvFYPhWMn8pXX6Nz6P6kmzpfQ1yDo
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
                binding: POST
                response-url: "{baseUrl}/logout/saml2/slo"
  application:
    name: spring-security-saml